/**
 * Lua Generator Module
 *
 * Converts JSON configuration to Lua code for DCS mission scripting.
 * This module can be used both by the Vue app and standalone Node.js CLI.
 */

// ==============================================================================
// LUA GENERATOR
// ==============================================================================

/**
 * Generate Lua code from units configuration
 * @param {Array} units - Array of unit configurations
 * @param {Object} refpointsStore - Reference points store
 * @param {Object} [options] - Options for generation
 * @param {boolean} [options.makeGlobal=false] - If true, UnitManifest will be global (not local) for easier testing
 * @param {Array} [options.routeTemplates] - Array of route templates to expand route references
 * @param {Array} [options.unitTemplates] - Array of unit templates to expand unit references
 * @returns {string} Generated Lua code
 */
export function generateLuaFromUnits(units, refpointsStore, options = {}) {
  const routeTemplates = options.routeTemplates || [];
  const routeTemplateMap = Object.fromEntries(routeTemplates.map(t => [t.id, t]));
  const unitTemplates = options.unitTemplates || [];
  const unitTemplateMap = Object.fromEntries(unitTemplates.map(t => [t.id, t]));
  const lines = [];
  lines.push('-- DCS Mission Lua Configuration');
  lines.push('-- Generated by DCS Mission Editor');
  lines.push('');
  lines.push('package.path = package.path .. ";../scripts/?.lua"');
  lines.push('');

  // Generate unit manifest
  lines.push('-- ==============================================================================');
  lines.push('-- UNIT MANIFEST');
  lines.push('-- ==============================================================================');
  lines.push('');
  lines.push(options.makeGlobal ? 'UnitManifest = {' : 'local UnitManifest = {');

  units.forEach((unit, index) => {
    if (index > 0) {
      lines.push(',');
    }
    lines.push('  -- ' + (unit.unitName || unit.groupName || 'Unit'));
    lines.push('  {');

    // Expand unit template if referenced
    // First copy unit, then apply template fields
    let unitToUse = { ...unit };
    if (unit.unitTemplate && unitTemplateMap[unit.unitTemplate]) {
      const template = unitTemplateMap[unit.unitTemplate];
      // Copy template fields that aren't units/route
      // The template may have routeTemplate that should be used
      for (const key in template) {
        if (key !== 'units' && key !== 'route') {
          unitToUse[key] = template[key];
        }
      }
    }

    // Unit properties
    if (unitToUse.enabled !== false) lines.push('    enabled = true,');
    if (unitToUse.triggerType) lines.push(`    triggerType = "${unitToUse.triggerType}",`);
    if (unitToUse.category) lines.push(`    category = "${unitToUse.category}",`);
    if (unitToUse.groupName) lines.push(`    groupName = "${unitToUse.groupName}",`);
    if (unitToUse.unitName && !unitToUse.groupName) lines.push(`    groupName = "${unitToUse.unitName}",`);
    if (unitToUse.country) lines.push(`    country = "${unitToUse.country}",`);
    if (unitToUse.task) lines.push(`    task = "${unitToUse.task}",`);
    if (unitToUse.frequency) lines.push(`    frequency = ${unitToUse.frequency},`);
    if (unitToUse.modulation) lines.push(`    modulation = "${unitToUse.modulation}",`);
    if (unitToUse.callsign) lines.push(`    callsign = "${unitToUse.callsign}",`);
    if (unitToUse.callsignNumber) lines.push(`    callsignNumber = ${unitToUse.callsignNumber},`);
    if (unitToUse.tacanChannel) lines.push(`    tacanChannel = "${unitToUse.tacanChannel}",`);
    if (unitToUse.radarFilterEnabled) lines.push(`    radarFilterEnabled = true,`);
    if (unitToUse.maxDetectRange) lines.push(`    maxDetectRange = ${unitToUse.maxDetectRange},`);
    if (unitToUse.zoneName) lines.push(`    zoneName = "${unitToUse.zoneName}",`);
    if (unitToUse.parentUnitName) lines.push(`    parentGroupName = "${unitToUse.parentUnitName}",`);
    if (unitToUse.parentGroupName) lines.push(`    parentGroupName = "${unitToUse.parentGroupName}",`);

    // Placement - use unit placement if provided, otherwise template placement
    let p = unit.placement;
    if (!p && unit.unitTemplate && unitToUse.placement) {
      p = unitToUse.placement;
    }
    if (p) {
      lines.push('    placement = {');

      // Handle different placement modes
      if (p.mode === 'AIRBASE_RAMP') {
        lines.push(`      startType = "takeoff_ramp",`);
        lines.push(`      airbaseName = "${p.referenceName || 'Unknown'}",`);
        if (p.parking) lines.push(`      groundSpot = ${p.parking},`);
      } else if (p.mode === 'BEARING_DISTANCE') {
        if (p.bearing !== undefined) lines.push(`      offsetHeading = ${p.bearing},`);
        if (p.distance !== undefined) lines.push(`      offsetDistance = ${p.distance},`);
        if (p.altitude !== undefined) lines.push(`      altitude = ${p.altitude},`);
        if (p.speed !== undefined) lines.push(`      speed = ${p.speed},`);
      } else if (p.mode === 'COORDINATE') {
        if (p.x !== undefined && p.y !== undefined) {
          lines.push(`      offsetX = ${p.x},`);
          lines.push(`      offsetY = ${p.y},`);
        }
      } else if (p.mode === 'ZONE_CENTER') {
        lines.push(`      strategy = "ZONE_RANDOM",`);
        lines.push(`      zoneName = "${p.referenceName || 'Unknown'}",`);
      }

      // Always set these fields (required by unit_management.lua template)
      lines.push(`      offsetX = 0,`);
      lines.push(`      offsetY = 0,`);

      // Always set strategy (required by unit_management.lua template)
      if (p.mode !== 'ZONE_CENTER') {
        lines.push(`      strategy = "",`);
      }
      // Always set spawnRadius (required by unit_management.lua template)
      lines.push(`      spawnRadius = 0,`);
      // Always set heading (required by unit_management.lua template)
      lines.push(`      heading = ${p.heading !== undefined ? p.heading : 0},`);

      lines.push('    },');
    }

    // Units array - merge template units with inline units (inline first)
    let unitsToUse = unitToUse.units || [];
    if (unitToUse.unitTemplate && unitTemplateMap[unitToUse.unitTemplate]) {
      const template = unitTemplateMap[unitToUse.unitTemplate];
      if (template.units && template.units.length > 0) {
        // Inline units come first, then append template units
        unitsToUse = [...unitsToUse, ...template.units];
      }
    }
    if (unitsToUse && unitsToUse.length > 0) {
      lines.push('    units = {');
      unitsToUse.forEach(u => {
        lines.push('      {');
        if (u.name) lines.push(`        name = "${u.name}",`);
        if (u.type || u.unitType) lines.push(`        unitType = "${u.type || u.unitType}",`);
        if (u.quantity !== undefined) lines.push(`        quantity = ${u.quantity},`);
        if (u.groundSpot) lines.push(`        groundSpot = ${u.groundSpot},`);
        lines.push('      },');
      });
      lines.push('    },');
    }

    // Handle route template reference - merge inline and template routes (inline first)
    let routeToUse = unitToUse.route || [];
    if (unitToUse.routeTemplate && routeTemplateMap[unitToUse.routeTemplate]) {
      // Use the expanded route template - append to inline route
      const template = routeTemplateMap[unitToUse.routeTemplate];
      if (template.route && template.route.length > 0) {
        routeToUse = [...routeToUse, ...template.route];
      }
    }

    // Route (always include, even if empty - required by template)
    lines.push('    route = {');
    if (routeToUse && routeToUse.length > 0) {
      routeToUse.forEach((wp, idx) => {
        if (idx > 0) lines.push(',');
        lines.push('      {');
        lines.push(`        type = "${wp.type || 'Turning Point'}",`);
        if (wp.altitude !== undefined) lines.push(`        alt = ${wp.altitude},`);
        if (wp.alt_type !== undefined) lines.push(`        alt_type = "${wp.alt_type}",`);
        if (wp.speed !== undefined) lines.push(`        speed = ${wp.speed},`);
        if (wp.x !== undefined) lines.push(`        offsetX = ${wp.x},`);
        if (wp.y !== undefined) lines.push(`        offsetY = ${wp.y},`);
        // Default offsetX/Y for orbit/other waypoint types that don't specify coordinates
        if (wp.x === undefined && wp.y === undefined) {
          lines.push('        offsetX = 0,');
          lines.push('        offsetY = 0,');
        }
        if (wp.radius !== undefined) lines.push(`        radius = ${wp.radius},`);
        if (wp.pattern) lines.push(`        pattern = "${wp.pattern}",`);
        if (wp.airbaseName) lines.push(`        airbaseName = "${wp.airbaseName}",`);
        lines.push('      }');
      });
    }
    lines.push('    },');

    // Point defense
    if (unit.pointDefense) {
      lines.push('    pointDefense = {');
      const pd = unit.pointDefense;
      if (pd.minRadius !== undefined) lines.push(`      minRadius = ${pd.minRadius},`);
      if (pd.maxRadius !== undefined) lines.push(`      maxRadius = ${pd.maxRadius},`);
      if (pd.units && pd.units.length > 0) {
        lines.push('      units = {');
        pd.units.forEach((u, idx) => {
          if (idx > 0) lines.push(',');
          if (typeof u === 'string') {
            lines.push(`        "${u}"`);
          } else if (u.type) {
            lines.push(`        "${u.type}"`);
          }
        });
        lines.push('      }');
      }
      lines.push('    },');
    }

    // Drone
    if (unit.drone) {
      lines.push('    drone = {');
      if (d.groupName) lines.push(`      groupName = "${d.groupName}",`);
      if (d.unitType) lines.push(`      unitType = "${d.unitType}",`);
      if (d.country) lines.push(`      country = "${d.country}",`);
      if (d.frequency) lines.push(`      frequency = ${d.frequency},`);
      if (d.callsign) lines.push(`      callsign = ${d.callsign},`);
      if (d.altitude !== undefined) lines.push(`      altitude = ${d.altitude},`);
      if (d.speed !== undefined) lines.push(`      speed = ${d.speed},`);
      lines.push('    },');
    }

    // Triggered units (for radar/ooc triggers) - use unit if provided, otherwise template
    let tu = unit.triggeredUnits;
    if (!tu && unitToUse.triggeredUnits) {
      tu = unitToUse.triggeredUnits;
    }
    if (tu) {
      lines.push('    triggeredUnits = {');
      if (tu.groupName) lines.push(`      groupName = "${tu.groupName}",`);
      if (tu.category) lines.push(`      category = "${tu.category}",`);
      if (tu.country) lines.push(`      country = "${tu.country}",`);
      if (tu.units) {
        lines.push('      units = {');
        tu.units.forEach(u => {
          if (typeof u === 'string') {
            lines.push(`        "${u}"`);
          } else if (u.type || u.unitType) {
            lines.push(`        "${u.type || u.unitType}"`);
          }
        });
        lines.push('      },');
      }
      if (tu.placement) {
        lines.push('      placement = {');
        if (tu.placement.x !== undefined && tu.placement.y !== undefined) {
          lines.push(`        offsetX = ${tu.placement.x},`);
          lines.push(`        offsetY = ${tu.placement.y},`);
        }
        lines.push('      },');
      }
      if (tu.route) {
        lines.push('      route = {');
        tu.route.forEach((wp, idx) => {
          if (idx > 0) lines.push(',');
          lines.push('        {');
          if (wp.x !== undefined) lines.push(`          offsetX = ${wp.x},`);
          if (wp.y !== undefined) lines.push(`          offsetY = ${wp.y},`);
          if (wp.altitude !== undefined) lines.push(`          alt = ${wp.altitude},`);
          if (wp.speed !== undefined) lines.push(`          speed = ${wp.speed},`);
          lines.push('        }');
        });
        lines.push('      },');
      }
      lines.push('    },');
    }

    lines.push('  }');
  });

  lines.push('};');
  lines.push('');

  // Generate start function
  lines.push('-- ==============================================================================');
  lines.push('-- MAIN ORCHESTRATION ENGINE INJECTION');
  lines.push('-- ==============================================================================');
  lines.push('');
  lines.push('function startDynamicTheatre()');
  lines.push('    -- Initialize units from manifest');
  lines.push('    if UnitManifest then');
  lines.push('        local units = MissionDirector.new(UnitManifest)');
  lines.push('        units:startEngineLoop()');
  lines.push('    end');
  lines.push('end');
  lines.push('');
  lines.push('-- Delay processing initialization execution by 3 seconds');
  lines.push('timer.scheduleFunction(startDynamicTheatre, {}, timer.getTime() + 3.0)');

  return lines.join('\n');
}

/**
 * Generate reference points section
 * @param {Object} refpointsStore - Reference points store
 * @returns {string} Lua code for reference points
 */
export function generateRefpointsSection(refpointsStore) {
  const lines = [];
  lines.push('-- ==============================================================================');
  lines.push('-- REFERENCE POINTS');
  lines.push('-- ==============================================================================');
  lines.push('');

  // Bullseyes
  lines.push('local Bullseyes = {');
  (refpointsStore.bullseyes || []).forEach(b => {
    lines.push(`  bullseye_${b.name.toLowerCase()} = { x = 0, y = 0 },  -- ${b.name}`);
  });
  lines.push('};');
  lines.push('');

  // Airbases
  lines.push('local Airbases = {');
  (refpointsStore.airbases || []).forEach(a => {
    lines.push(`  ${a.name} = { x = 0, y = 0 },  -- Airbase coordinates would be loaded from DCS`);
  });
  lines.push('};');
  lines.push('');

  // Zones
  lines.push('local Zones = {');
  (refpointsStore.zones || []).forEach(z => {
    lines.push(`  ["${z.name}"] = true,`);
  });
  lines.push('};');
  lines.push('');

  // Lines
  lines.push('local Lines = {');
  (refpointsStore.lines || []).forEach(l => {
    lines.push(`  ["${l.name}"] = { startX = ${l.startX || 0}, startY = ${l.startY || 0}, endX = ${l.endX || 0}, endY = ${l.endY || 0} },`);
  });
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}
