/**
 * Lua Generator Module
 *
 * Converts JSON configuration to Lua code for DCS mission scripting.
 * This module can be used both by the Vue app and standalone Node.js CLI.
 */

// ==============================================================================
// LUA GENERATOR
// ==============================================================================

/**
 * Generate Lua code from units configuration
 * @param {Array} units - Array of unit configurations
 * @param {Object} refpointsStore - Reference points store
 * @param {Object} [options] - Options for generation
 * @param {boolean} [options.makeGlobal=false] - If true, UnitManifest will be global (not local) for easier testing
 * @returns {string} Generated Lua code
 */
export function generateLuaFromUnits(units, refpointsStore, options = {}) {
  const lines = [];
  lines.push('-- DCS Mission Lua Configuration');
  lines.push('-- Generated by DCS Mission Editor');
  lines.push('');
  lines.push('package.path = package.path .. ";../scripts/?.lua"');
  lines.push('');

  // Generate unit manifest
  lines.push('-- ==============================================================================');
  lines.push('-- UNIT MANIFEST');
  lines.push('-- ==============================================================================');
  lines.push('');
  lines.push(options.makeGlobal ? 'UnitManifest = {' : 'local UnitManifest = {');

  units.forEach((unit, index) => {
    if (index > 0) {
      lines.push(',');
    }
    lines.push('  -- ' + (unit.unitName || unit.groupName || 'Unit'));
    lines.push('  {');

    // Unit properties
    if (unit.enabled !== false) lines.push('    enabled = true,');
    if (unit.triggerType) lines.push(`    triggerType = "${unit.triggerType}",`);
    if (unit.category) lines.push(`    category = "${unit.category}",`);
    if (unit.groupName) lines.push(`    groupName = "${unit.groupName}",`);
    if (unit.unitName && !unit.groupName) lines.push(`    groupName = "${unit.unitName}",`);
    if (unit.country) lines.push(`    country = "${unit.country}",`);
    if (unit.task) lines.push(`    task = "${unit.task}",`);
    if (unit.frequency) lines.push(`    frequency = ${unit.frequency},`);
    if (unit.modulation) lines.push(`    modulation = "${unit.modulation}",`);
    if (unit.callsign) lines.push(`    callsign = "${unit.callsign}",`);
    if (unit.callsignNumber) lines.push(`    callsignNumber = ${unit.callsignNumber},`);
    if (unit.tacanChannel) lines.push(`    tacanChannel = "${unit.tacanChannel}",`);
    if (unit.radarFilterEnabled) lines.push(`    radarFilterEnabled = true,`);
    if (unit.maxDetectRange) lines.push(`    maxDetectRange = ${unit.maxDetectRange},`);
    if (unit.zoneName) lines.push(`    zoneName = "${unit.zoneName}",`);
    if (unit.parentUnitName) lines.push(`    parentGroupName = "${unit.parentUnitName}",`);
    if (unit.parentGroupName) lines.push(`    parentGroupName = "${unit.parentGroupName}",`);

    // Placement
    if (unit.placement) {
      lines.push('    placement = {');
      const p = unit.placement;

      // Handle different placement modes
      if (p.mode === 'AIRBASE_RAMP') {
        lines.push(`      startType = "takeoff_ramp",`);
        lines.push(`      airbaseName = "${p.referenceName || 'Unknown'}",`);
        if (p.parking) lines.push(`      groundSpot = ${p.parking},`);
      } else if (p.mode === 'BEARING_DISTANCE') {
        if (p.bearing !== undefined) lines.push(`      offsetHeading = ${p.bearing},`);
        if (p.distance !== undefined) lines.push(`      offsetDistance = ${p.distance},`);
        if (p.heading !== undefined) lines.push(`      heading = ${p.heading},`);
        if (p.altitude !== undefined) lines.push(`      altitude = ${p.altitude},`);
        if (p.speed !== undefined) lines.push(`      speed = ${p.speed},`);
      } else if (p.mode === 'COORDINATE') {
        if (p.x !== undefined && p.y !== undefined) {
          lines.push(`      offsetX = ${p.x},`);
          lines.push(`      offsetY = ${p.y},`);
        }
        if (p.heading !== undefined) lines.push(`      heading = ${p.heading},`);
      } else if (p.mode === 'ZONE_CENTER') {
        lines.push(`      strategy = "ZONE_RANDOM",`);
        lines.push(`      zoneName = "${p.referenceName || 'Unknown'}",`);
      }

      lines.push('    },');
    }

    // Units array (aircraft/ground units within a group)
    if (unit.units && unit.units.length > 0) {
      lines.push('    units = {');
      unit.units.forEach(u => {
        lines.push('      {');
        if (u.name) lines.push(`        name = "${u.name}",`);
        if (u.type || u.unitType) lines.push(`        unitType = "${u.type || u.unitType}",`);
        if (u.quantity !== undefined) lines.push(`        quantity = ${u.quantity},`);
        if (u.groundSpot) lines.push(`        groundSpot = ${u.groundSpot},`);
        lines.push('      },');
      });
      lines.push('    },');
    }

    // Route
    if (unit.route && unit.route.length > 0) {
      lines.push('    route = {');
      unit.route.forEach((wp, idx) => {
        if (idx > 0) lines.push(',');
        lines.push('      {');
        lines.push(`        type = "${wp.type || 'Turning Point'}",`);
        if (wp.altitude !== undefined) lines.push(`        alt = ${wp.altitude},`);
        if (wp.altType !== undefined) lines.push(`       alt_type = ${wp.altType},`)
        if (wp.speed !== undefined) lines.push(`        speed = ${wp.speed},`);
        if (wp.x !== undefined) lines.push(`        offsetX = ${wp.x},`);
        if (wp.y !== undefined) lines.push(`        offsetY = ${wp.y},`);
        if (wp.radius !== undefined) lines.push(`        radius = ${wp.radius},`);
        if (wp.pattern) lines.push(`        pattern = "${wp.pattern}",`);
        if (wp.heading !== undefined) lines.push(`        heading = ${wp.heading},`);
        if (wp.airbaseName) lines.push(`        airbaseName = "${wp.airbaseName}",`);
        lines.push('      }');
      });
      lines.push('    },');
    }

    // Point defense
    if (unit.pointDefense) {
      lines.push('    pointDefense = {');
      const pd = unit.pointDefense;
      if (pd.minRadius !== undefined) lines.push(`      minRadius = ${pd.minRadius},`);
      if (pd.maxRadius !== undefined) lines.push(`      maxRadius = ${pd.maxRadius},`);
      if (pd.units && pd.units.length > 0) {
        lines.push('      units = {');
        pd.units.forEach((u, idx) => {
          if (idx > 0) lines.push(',');
          if (typeof u === 'string') {
            lines.push(`        "${u}"`);
          } else if (u.type) {
            lines.push(`        "${u.type}"`);
          }
        });
        lines.push('      }');
      }
      lines.push('    },');
    }

    // Drone
    if (unit.drone) {
      lines.push('    drone = {');
      const d = unit.drone;
      if (d.groupName) lines.push(`      groupName = "${d.groupName}",`);
      if (d.unitType) lines.push(`      unitType = "${d.unitType}",`);
      if (d.country) lines.push(`      country = "${d.country}",`);
      if (d.frequency) lines.push(`      frequency = ${d.frequency},`);
      if (d.callsign) lines.push(`      callsign = ${d.callsign},`);
      if (d.altitude !== undefined) lines.push(`      altitude = ${d.altitude},`);
      if (d.speed !== undefined) lines.push(`      speed = ${d.speed},`);
      lines.push('    },');
    }

    // Triggered units (for radar/ooc triggers)
    if (unit.triggeredUnits) {
      lines.push('    triggeredUnits = {');
      const tu = unit.triggeredUnits;
      if (tu.groupName) lines.push(`      groupName = "${tu.groupName}",`);
      if (tu.category) lines.push(`      category = "${tu.category}",`);
      if (tu.country) lines.push(`      country = "${tu.country}",`);
      if (tu.units) {
        lines.push('      units = {');
        tu.units.forEach(u => {
          if (typeof u === 'string') {
            lines.push(`        "${u}"`);
          } else if (u.type || u.unitType) {
            lines.push(`        "${u.type || u.unitType}"`);
          }
        });
        lines.push('      },');
      }
      if (tu.placement) {
        lines.push('      placement = {');
        if (tu.placement.x !== undefined && tu.placement.y !== undefined) {
          lines.push(`        offsetX = ${tu.placement.x},`);
          lines.push(`        offsetY = ${tu.placement.y},`);
        }
        lines.push('      },');
      }
      if (tu.route) {
        lines.push('      route = {');
        tu.route.forEach((wp, idx) => {
          if (idx > 0) lines.push(',');
          lines.push('        {');
          if (wp.x !== undefined) lines.push(`          offsetX = ${wp.x},`);
          if (wp.y !== undefined) lines.push(`          offsetY = ${wp.y},`);
          if (wp.altitude !== undefined) lines.push(`          alt = ${wp.altitude},`);
          if (wp.speed !== undefined) lines.push(`          speed = ${wp.speed},`);
          lines.push('        }');
        });
        lines.push('      },');
      }
      lines.push('    },');
    }

    lines.push('  }');
  });

  lines.push('};');
  lines.push('');

  // Generate start function
  lines.push('-- ==============================================================================');
  lines.push('-- MAIN ORCHESTRATION ENGINE INJECTION');
  lines.push('-- ==============================================================================');
  lines.push('');
  lines.push('function startDynamicTheatre()');
  lines.push('    -- Initialize units from manifest');
  lines.push('    if UnitManifest then');
  lines.push('        local units = MissionDirector.new(UnitManifest)');
  lines.push('        units:startEngineLoop()');
  lines.push('    end');
  lines.push('end');
  lines.push('');
  lines.push('-- Delay processing initialization execution by 3 seconds');
  lines.push('timer.scheduleFunction(startDynamicTheatre, {}, timer.getTime() + 3.0)');

  return lines.join('\n');
}

/**
 * Generate reference points section
 * @param {Object} refpointsStore - Reference points store
 * @returns {string} Lua code for reference points
 */
export function generateRefpointsSection(refpointsStore) {
  const lines = [];
  lines.push('-- ==============================================================================');
  lines.push('-- REFERENCE POINTS');
  lines.push('-- ==============================================================================');
  lines.push('');

  // Bullseyes
  lines.push('local Bullseyes = {');
  (refpointsStore.bullseyes || []).forEach(b => {
    lines.push(`  bullseye_${b.name.toLowerCase()} = { x = 0, y = 0 },  -- ${b.name}`);
  });
  lines.push('};');
  lines.push('');

  // Airbases
  lines.push('local Airbases = {');
  (refpointsStore.airbases || []).forEach(a => {
    lines.push(`  ${a.name} = { x = 0, y = 0 },  -- Airbase coordinates would be loaded from DCS`);
  });
  lines.push('};');
  lines.push('');

  // Zones
  lines.push('local Zones = {');
  (refpointsStore.zones || []).forEach(z => {
    lines.push(`  ["${z.name}"] = true,`);
  });
  lines.push('};');
  lines.push('');

  // Lines
  lines.push('local Lines = {');
  (refpointsStore.lines || []).forEach(l => {
    lines.push(`  ["${l.name}"] = { startX = ${l.startX || 0}, startY = ${l.startY || 0}, endX = ${l.endX || 0}, endY = ${l.endY || 0} },`);
  });
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}
