-- DCS Mission Lua Configuration
-- Generated by DCS Mission Editor

package.path = package.path .. ";../scripts/?.lua"

-- ==============================================================================
-- UNIT MANIFEST
-- ==============================================================================

UnitManifest = {
  -- Blue_AWACS_Support
  {
    enabled = true,
    triggerType = "IMMEDIATE",
    category = "AIRPLANE",
    groupName = "Blue_AWACS_Support",
    country = "USA",
    placement = {
      offsetHeading = 0,
      offsetDistance = 3,
      strategy = "BEARING_DISTANCE",
      offsetX = 0,
      offsetY = 0,
      spawnRadius = 0,
      heading = 0,
    },
    units = {
      {
        name = "AWACS Lead",
        unitType = "E-3A",
        quantity = 1,
      },
    },
    route = {
      {
        type = "orbit",
        alt = 30000,
        alt_type = "BARO",
        speed = 280,
        offsetX = 0,
        offsetY = 0,
        radius = 25,
        pattern = "clockwise",
      }
    },
  }
,
  -- Blue_Home_Base_Assets
  {
    enabled = true,
    triggerType = "IMMEDIATE",
    category = "GROUND",
    groupName = "Blue_Home_Base_Assets",
    country = "USA",
    placement = {
      strategy = "waypoint",
      groupName = "Unknown",
      waypoint = 1,
      offsetX = 0,
      offsetY = 0,
      spawnRadius = 0,
      heading = 0,
    },
    units = {
      {
        name = "Logistics Truck",
        unitType = "MT-LB",
        quantity = 2,
      },
    },
    route = {
    },
  }
,
  -- Blue_Alt_Airfield_Assets
  {
    enabled = true,
    triggerType = "IMMEDIATE",
    category = "GROUND",
    groupName = "Blue_Alt_Airfield_Assets",
    country = "USA",
    placement = {
      strategy = "waypoint",
      groupName = "Unknown",
      waypoint = 2,
      offsetX = 0,
      offsetY = 0,
      spawnRadius = 0,
      heading = 0,
    },
    units = {
      {
        name = "Logistics Truck",
        unitType = "MT-LB",
        quantity = 2,
      },
    },
    route = {
    },
  }
,
  -- Blue_Tanker_Support
  {
    enabled = true,
    triggerType = "IMMEDIATE",
    category = "AIRPLANE",
    groupName = "Blue_Tanker_Support",
    country = "USA",
    placement = {
      strategy = "waypoint",
      groupName = "Unknown",
      waypoint = 4,
      offsetX = 0,
      offsetY = 0,
      spawnRadius = 0,
      heading = 0,
    },
    units = {
      {
        name = "Tanker",
        unitType = "KC-135",
        quantity = 2,
      },
    },
    route = {
    },
  }
,
  -- Red_Outpost_Elements
  {
    enabled = true,
    triggerType = "IMMEDIATE",
    category = "GROUND",
    groupName = "Red_Outpost_Elements",
    country = "Russia",
    placement = {
      strategy = "ZONE_RANDOM",
      zoneName = "Ridge_Line_Alpha",
      offsetX = 0,
      offsetY = 0,
      spawnRadius = 0.5,
      heading = 180,
    },
    units = {
      {
        name = "Scout Lead",
        unitType = "BMP-2",
        quantity = 3,
      },
      {
        name = "Recon Support",
        unitType = "BRDM-2",
        quantity = 2,
      },
    },
    route = {
      {
        type = "Off Road",
        speed = 25,
        offsetX = 0,
        offsetY = 0,
      }
    },
  }
,
  -- Blue_Forward_Support
  {
    enabled = true,
    triggerType = "IMMEDIATE",
    category = "GROUND",
    groupName = "Blue_Forward_Support",
    country = "USA",
    placement = {
      offsetHeading = 0,
      offsetDistance = 2,
      strategy = "BEARING_DISTANCE",
      offsetX = 0,
      offsetY = 0,
      spawnRadius = 0,
      heading = 180,
    },
    units = {
      {
        name = "Support Lead",
        unitType = "M2_Bradley",
        quantity = 4,
      },
      {
        name = "Mortar_Section",
        unitType = "M109_Paladin",
        quantity = 2,
      },
    },
    route = {
    },
  }
,
  -- Russian_Rapid_Response_Air
  {
    enabled = true,
    triggerType = "OBJECTIVE_COMPLETE",
    category = "AIRPLANE",
    groupName = "Russian_Rapid_Response_Air",
    country = "Russia",
    parentGroupName = "Red_Outpost_Elements",
    placement = {
      strategy = "COORDINATE",
      offsetX = 0,
      offsetY = 10,
      spawnRadius = 0,
      heading = 0,
    },
    units = {
      {
        name = "Strike Lead",
        unitType = "Su-25SM3",
        quantity = 4,
      },
      {
        name = "Escort",
        unitType = "MiG-29",
        quantity = 2,
      },
    },
    route = {
      {
        type = "orbit",
        alt = 25000,
        alt_type = "BARO",
        speed = 350,
        offsetX = 0,
        offsetY = 0,
        radius = 15,
        pattern = "clockwise",
      }
,
      {
        type = "orbit",
        alt = 25000,
        alt_type = "BARO",
        speed = 350,
        offsetX = 0,
        offsetY = 0,
        radius = 15,
        pattern = "clockwise",
      }
    },
  }
,
  -- Red_Iron_Fist_Column
  {
    enabled = true,
    triggerType = "OBJECTIVE_COMPLETE",
    category = "GROUND",
    groupName = "Red_Iron_Fist_Column",
    country = "Russia",
    parentGroupName = "Red_Outpost_Elements",
    placement = {
      offsetHeading = 0,
      offsetDistance = 5,
      strategy = "BEARING_DISTANCE",
      offsetX = 0,
      offsetY = 0,
      spawnRadius = 0,
      heading = 180,
    },
    units = {
      {
        name = "Main Battle Tank",
        unitType = "T-90M",
        quantity = 6,
      },
      {
        name = "Mechanized Support",
        unitType = "BMP-3",
        quantity = 4,
      },
      {
        name = "Mobile AA",
        unitType = "Pantsir-S1",
        quantity = 2,
      },
    },
    route = {
      {
        type = "On Road",
        speed = 35,
        offsetX = 0,
        offsetY = 0,
      }
    },
  }
,
  -- Red_Guards_QRF
  {
    enabled = true,
    triggerType = "OBJECTIVE_COMPLETE",
    category = "GROUND",
    groupName = "Red_Guards_QRF",
    country = "Russia",
    parentGroupName = "Red_Iron_Fist_Column",
    placement = {
      offsetHeading = 0,
      offsetDistance = 2.5,
      strategy = "BEARING_DISTANCE",
      offsetX = 0,
      offsetY = 0,
      spawnRadius = 0,
      heading = 270,
    },
    units = {
      {
        name = "Heavy Tank",
        unitType = "T-90M",
        quantity = 10,
      },
      {
        name = "Infantry Carrier",
        unitType = "BMP-3",
        quantity = 6,
      },
    },
    route = {
      {
        type = "On Road",
        speed = 35,
        offsetX = 0,
        offsetY = 0,
      }
    },
  }
};

-- ==============================================================================
-- MAIN ORCHESTRATION ENGINE INJECTION
-- ==============================================================================

function startDynamicTheatre()
    -- Initialize units from manifest
    if UnitManifest then
        local units = MissionDirector.new(UnitManifest)
        units:startEngineLoop()
    end
end

-- Delay processing initialization execution by 3 seconds
timer.scheduleFunction(startDynamicTheatre, {}, timer.getTime() + 3.0)